esphome:
  name: PKIO230
  friendly_name: Prokyber PKIO230P

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "EBUjI5WvGIlhVMJd9LjAGqPQpicF3tL6zDv6qaRiVpo="

ota:
  - platform: esphome
  #  password: "bb8e8de908cb6bec24572f9450c58275"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


i2c:
  sda: GPIO13
  scl: GPIO14
  scan: true
  id: bus_a

pcf8574:
  - id: 'PKIO230'
    address: 0x21
    pcf8575: false

binary_sensor:
  - platform: gpio
    name: "Input 0"
    pin:
      pcf8574: PKIO230
      number: 0
      mode: 
        input: true
      inverted: true
  - platform: gpio
    name: "Input 1"
    pin:
      pcf8574: PKIO230
      number: 1
      mode: 
        input: true
      inverted: true
  - platform: gpio
    name: "Input 2"
    pin:
      pcf8574: PKIO230
      number: 2
      mode: 
        input: true
      inverted: true
  - platform: gpio
    name: "Input 3"
    pin:
      pcf8574: PKIO230
      number: 3
      mode: 
        input: true
      inverted: true

switch:
  - platform: gpio
    name: "Relay 4"
    pin:
      pcf8574: PKIO230
      number: 4
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Relay 5"
    pin:
      pcf8574: PKIO230
      number: 5
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Relay 6"
    pin:
      pcf8574: PKIO230
      number: 6
      mode:
        output: true
      inverted: false
  - platform: gpio
    name: "Relay 7"
    pin:
      pcf8574: PKIO230
      number: 7
      mode:
        output: true
      inverted: false